language: ruby

services:
  - postgresql

addons:
  - snaps:
    - name: docker
      channel: latest/beta
  - postgresql: "12.1"

cache:
  directories:
    - vendor/bundle

rvm: "2.6.3"

env:
  - RAILS_ENV=test
  - global:
    - PATH=/snap/bin:$PATH

before_script:
  - cp db/structure.sql db/structure-original.sql
  - cp config/database.yml.travis config/database.yml

after_success:
  - script/upload_structure.rb


jobs:
  include:
    - stage: "Testing time"
      script:
        - bundle exec rspec spec
        - script/validate_structure_file.rb db/structure-original.sql
